### ISSUE TITLE
在项目里怎么找到traefik的配置文件？

### ISSUE THREAD

**Issue by i-rework** [homeinfra-org/infra#2]
请告诉我，在项目里怎么找到traefik的配置文件？
我观察到 https://github.com/homeinfra-org/infra 项目里，没有和traefik项目相关的docker-compose配置。但是项目里README.md提到使用了traefik。

**Comment by NoCLin** [comment]
Hi @i-rework，谢谢反馈。

在 [这个PR ](https://github.com/homeinfra-org/infra/pull/1/files) 我把traefik 切换为Caddy了，因为配置更简洁，需要的话可以看上一个版本的代码。
~文档我更新一下。~
文档更新好了。
