### ISSUE TITLE
与Cloudflare相关的CLOUDFLARE_DNS_API_TOKEN怎么申请？

### ISSUE THREAD

**Issue by i-rework** [homeinfra-org/infra#3]
谢谢上一个Issue对traefik问题的回复！:)

我注意到Caddy目录下.env里，需要设置 CLOUDFLARE_DNS_API_TOKEN，请问应该怎么设置？

**Comment by NoCLin** [comment]
请参考 https://developers.cloudflare.com/fundamentals/api/get-started/create-token/  谢谢。
