### ISSUE TITLE
Change "deamon" to "daemon" in gitea_runner's config file

### ISSUE THREAD

**Issue by yy-zhong** [homeinfra-org/infra#4]
https://github.com/homeinfra-org/infra/blob/ca44013973f427fa93c799a51f51852063006790/docker/gitea_runner/config.yaml#L35

I think the "deamon" should be replaced as "daemon", the gitea doesn't provide a "deamon" configuration.

**Comment by NoCLin** [comment]
@zhong-yiyu Thanks for your feedback. 

It's a typo and [this](https://gitea.com/gitea/act_runner/commit/a5085dde0cefcb87e9157aa055868860ca7ce1e7) is the update from upstream. Will update the config file in the future.
